# Change these first
owner: kappaml # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: KappaML
    url: https://www.kappaml.com
  - name: KappaML API Docs
    url: https://api.kappaml.com/docs
  - name: KappaML Application
    url: https://app.kappaml.com


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kappaml.com
  logoUrl: https://www.kappaml.com/img/logo.svg
  name: KappaML
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/KappaML
    - title: KappaML
      href: https://www.kappaml.com
